version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: lde.nginx
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NGINX_PORT=80
    ports:
      - "80:80"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    image: postgres:alpine
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8001:80"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:alpine
    container_name: lde.redis
    ports:
      - "6380:6379"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: ./IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5002
      - GlobalUrl=http://host.docker.internal
      - CatalogApi=http://host.docker.internal:5000
      - SpaUrl=http://host.docker.internal
      - IdentityUrl=http://host.docker.internal:5002
      - BasketApi=http://host.docker.internal:5003
    ports:
      - "5002:5002"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: ./Catalog/Catalog.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - Authorization__Authority=http://host.docker.internal:5002
      - ConnectionString=server=host.docker.internal;port=5433;database=catalog;uid=postgres;password=postgres;
      - PathBase=http://host.docker.internal:5000
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: ./Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://host.docker.internal:5002
      - Redis__Host=host.docker.internal:6380
      - Redis__CacheTimeout=48:00:00
      - PathBase=http://host.docker.internal:5003
    depends_on:
      - redis
    ports:
      - "5003:5003"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  web.client:
    container_name: lde.web.client
    build:
      context: ./Web/Web.Client
      dockerfile: ./Dockerfile.prod
      target: production
    volumes:
      - ./Web/Web.Client/public:/app/public
      - ./Web/Web.Client/src:/app/src
    env_file:
      - ./Web/Web.Client/.env.docker.production
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
      - "5001:5001"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
