@echo off

cd /d %~dp0

call codium --install-extension aaron-bond.better-comments
call codium --install-extension alefragnani.Bookmarks
call codium --install-extension alefragnani.project-manager
call codium --install-extension amazonwebservices.aws-toolkit-vscode
call codium --install-extension arcanis.vscode-zipfs
call codium --install-extension benspaulding.procfile
call codium --install-extension burkeholland.simple-react-snippets
call codium --install-extension capaj.vscode-standardjs-snippets
call codium --install-extension christian-kohler.npm-intellisense
call codium --install-extension christian-kohler.path-intellisense
call codium --install-extension codezombiech.gitignore
call codium --install-extension DavidAnson.vscode-markdownlint
call codium --install-extension dbaeumer.vscode-eslint
call codium --install-extension declanzou.index-generator
call codium --install-extension deque-systems.vscode-axe-linter
call codium --install-extension donjayamanne.git-extension-pack
call codium --install-extension donjayamanne.githistory
call codium --install-extension dozerg.tsimportsorter
call codium --install-extension dracula-theme.theme-dracula
call codium --install-extension eamodio.gitlens
call codium --install-extension EditorConfig.EditorConfig
call codium --install-extension esbenp.prettier-vscode
call codium --install-extension felipecaputo.git-project-manager
call codium --install-extension firefox-devtools.vscode-firefox-debug
call codium --install-extension flowtype.flow-for-vscode
call codium --install-extension formulahendry.code-runner
call codium --install-extension GitHub.github-vscode-theme
call codium --install-extension github.vscode-pull-request-github
call codium --install-extension glenn2223.live-sass
call codium --install-extension googlecloudtools.cloudcode
call codium --install-extension GrapeCity.gc-excelviewer
call codium --install-extension Gruntfuggly.todo-tree
call codium --install-extension humao.rest-client
call codium --install-extension IronGeek.vscode-env
call codium --install-extension ivangabriele.vscode-heroku
call codium --install-extension JayFong.generate-index
call codium --install-extension jbockle.jbockle-format-files
call codium --install-extension JounQin.vscode-mdx
call codium --install-extension lacroixdavid1.vscode-format-context-menu
call codium --install-extension logerfo.procfile-support
call codium --install-extension mark-tucker.aws-cli-configure
call codium --install-extension mgmcdermott.vscode-language-babel
call codium --install-extension mhutchie.git-graph
call codium --install-extension mindaro-dev.file-downloader
call codium --install-extension mindaro.mindaro
call codium --install-extension mohsen1.react-javascript-to-typescript-transform-vscode
call codium --install-extension ms-azuretools.vscode-azureappservice
call codium --install-extension ms-azuretools.vscode-docker
call codium --install-extension MS-CEINTL.vscode-language-pack-ru
call codium --install-extension ms-dotnettools.csharp
call codium --install-extension ms-edgedevtools.vscode-edge-devtools
call codium --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
call codium --install-extension ms-mssql.data-workspace-vscode
call codium --install-extension ms-mssql.mssql
call codium --install-extension ms-mssql.sql-bindings-vscode
call codium --install-extension ms-mssql.sql-database-projects-vscode
call codium --install-extension ms-vscode-remote.remote-containers
call codium --install-extension ms-vscode-remote.remote-ssh
call codium --install-extension ms-vscode-remote.remote-ssh-edit
call codium --install-extension ms-vscode-remote.remote-wsl
call codium --install-extension ms-vscode-remote.vscode-remote-extensionpack
call codium --install-extension ms-vscode.hexeditor
call codium --install-extension ms-vscode.notepadplusplus-keybindings
call codium --install-extension ms-vscode.powershell
call codium --install-extension ms-vscode.vscode-typescript-next
call codium --install-extension mscolnick.export-typescript
call codium --install-extension Orta.vscode-jest
call codium --install-extension PKief.material-icon-theme
call codium --install-extension pkosta2005.heroku-command
call codium --install-extension redhat.vscode-yaml
call codium --install-extension ritwickdey.LiveServer
call codium --install-extension samverschueren.linter-xo
call codium --install-extension shd101wyy.markdown-preview-enhanced
call codium --install-extension sourcegraph.sourcegraph
call codium --install-extension sourcegraph.vscode-sourcegraph-theme
call codium --install-extension standard.vscode-standard
call codium --install-extension streetsidesoftware.code-spell-checker
call codium --install-extension streetsidesoftware.code-spell-checker-russian
call codium --install-extension streetsidesoftware.code-spell-checker-ukrainian
call codium --install-extension stylelint.vscode-stylelint
call codium --install-extension temitope1909.dotenv-intellisense
call codium --install-extension TimonVS.ReactSnippetsStandard
call codium --install-extension unifiedjs.vscode-remark
call codium --install-extension unional.vscode-sort-package-json
call codium --install-extension VisualStudioExptTeam.vscodeintellicode
call codium --install-extension vscode-icons-team.vscode-icons
call codium --install-extension wayou.vscode-todo-highlight
call codium --install-extension xabikos.JavaScriptSnippets
call codium --install-extension yzhang.markdown-all-in-one
call codium --install-extension ziyasal.vscode-open-in-github

pause
