@echo off

cd /d %~dp0

call code --install-extension aaron-bond.better-comments
call code --install-extension alefragnani.Bookmarks
call code --install-extension alefragnani.project-manager
call code --install-extension amazonwebservices.aws-toolkit-vscode
call code --install-extension arcanis.vscode-zipfs
call code --install-extension benspaulding.procfile
call code --install-extension burkeholland.simple-react-snippets
call code --install-extension capaj.vscode-standardjs-snippets
call code --install-extension christian-kohler.npm-intellisense
call code --install-extension christian-kohler.path-intellisense
call code --install-extension codezombiech.gitignore
call code --install-extension DavidAnson.vscode-markdownlint
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension declanzou.index-generator
call code --install-extension deque-systems.vscode-axe-linter
call code --install-extension donjayamanne.git-extension-pack
call code --install-extension donjayamanne.githistory
call code --install-extension dozerg.tsimportsorter
call code --install-extension dracula-theme.theme-dracula
call code --install-extension eamodio.gitlens
call code --install-extension EditorConfig.EditorConfig
call code --install-extension esbenp.prettier-vscode
call code --install-extension felipecaputo.git-project-manager
call code --install-extension firefox-devtools.vscode-firefox-debug
call code --install-extension flowtype.flow-for-vscode
call code --install-extension formulahendry.code-runner
call code --install-extension GitHub.github-vscode-theme
call code --install-extension github.vscode-pull-request-github
call code --install-extension glenn2223.live-sass
call code --install-extension googlecloudtools.cloudcode
call code --install-extension GrapeCity.gc-excelviewer
call code --install-extension Gruntfuggly.todo-tree
call code --install-extension humao.rest-client
call code --install-extension IronGeek.vscode-env
call code --install-extension ivangabriele.vscode-heroku
call code --install-extension JayFong.generate-index
call code --install-extension jbockle.jbockle-format-files
call code --install-extension JounQin.vscode-mdx
call code --install-extension lacroixdavid1.vscode-format-context-menu
call code --install-extension logerfo.procfile-support
call code --install-extension mark-tucker.aws-cli-configure
call code --install-extension mgmcdermott.vscode-language-babel
call code --install-extension mhutchie.git-graph
call code --install-extension mindaro-dev.file-downloader
call code --install-extension mindaro.mindaro
call code --install-extension mohsen1.react-javascript-to-typescript-transform-vscode
call code --install-extension ms-azuretools.vscode-azureappservice
call code --install-extension ms-azuretools.vscode-docker
call code --install-extension MS-CEINTL.vscode-language-pack-ru
call code --install-extension ms-dotnettools.csharp
call code --install-extension ms-edgedevtools.vscode-edge-devtools
call code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
call code --install-extension ms-mssql.data-workspace-vscode
call code --install-extension ms-mssql.mssql
call code --install-extension ms-mssql.sql-bindings-vscode
call code --install-extension ms-mssql.sql-database-projects-vscode
call code --install-extension ms-vscode-remote.remote-containers
call code --install-extension ms-vscode-remote.remote-ssh
call code --install-extension ms-vscode-remote.remote-ssh-edit
call code --install-extension ms-vscode-remote.remote-wsl
call code --install-extension ms-vscode-remote.vscode-remote-extensionpack
call code --install-extension ms-vscode.hexeditor
call code --install-extension ms-vscode.notepadplusplus-keybindings
call code --install-extension ms-vscode.powershell
call code --install-extension ms-vscode.vscode-typescript-next
call code --install-extension mscolnick.export-typescript
call code --install-extension Orta.vscode-jest
call code --install-extension PKief.material-icon-theme
call code --install-extension pkosta2005.heroku-command
call code --install-extension redhat.vscode-yaml
call code --install-extension ritwickdey.LiveServer
call code --install-extension samverschueren.linter-xo
call code --install-extension shd101wyy.markdown-preview-enhanced
call code --install-extension sourcegraph.sourcegraph
call code --install-extension sourcegraph.vscode-sourcegraph-theme
call code --install-extension standard.vscode-standard
call code --install-extension streetsidesoftware.code-spell-checker
call code --install-extension streetsidesoftware.code-spell-checker-russian
call code --install-extension streetsidesoftware.code-spell-checker-ukrainian
call code --install-extension stylelint.vscode-stylelint
call code --install-extension temitope1909.dotenv-intellisense
call code --install-extension TimonVS.ReactSnippetsStandard
call code --install-extension unifiedjs.vscode-remark
call code --install-extension unional.vscode-sort-package-json
call code --install-extension VisualStudioExptTeam.vscodeintellicode
call code --install-extension vscode-icons-team.vscode-icons
call code --install-extension wayou.vscode-todo-highlight
call code --install-extension xabikos.JavaScriptSnippets
call code --install-extension yzhang.markdown-all-in-one
call code --install-extension ziyasal.vscode-open-in-github

pause
