version: "3.9"

services:
  nginx:
    volumes:
      - ../../Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ../../Proxy/assets:/var/www/assets
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - NGINX_PORT=80
    ports:
      - "80:80"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  pgadmin4:
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8001:80"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    ports:
      - "6380:6379"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - GlobalUrl=http://host.docker.internal
      - CatalogApi=http://host.docker.internal:5000
      - SpaUrl=http://host.docker.internal:5001
      - IdentityUrl=http://host.docker.internal:5002
      - BasketApi=http://host.docker.internal:5003
    ports:
      - "5002:5002"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  catalog.api:
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Authorization__Authority=http://host.docker.internal:5002
      - ConnectionString=server=host.docker.internal;port=5433;database=catalog;uid=postgres;password=postgres;
      - PathBase=http://host.docker.internal:5000
    ports:
      - "5000:5000"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"

  basket.api:
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://host.docker.internal:5002
      - Redis__Host=host.docker.internal:6380
      - Redis__CacheTimeout=48:00:00
      - PathBase=http://host.docker.internal:5003
    ports:
      - "5003:5003"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
